package cn.hshb.web.biz.mybatis.model;

public class CommonRentType extends CommonRentTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_rent_type.rent_type_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String rentTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_rent_type.rent_value
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer rentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_rent_type.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_rent_type.rent_type_name
     *
     * @return the value of common_rent_type.rent_type_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getRentTypeName() {
        return rentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_rent_type.rent_type_name
     *
     * @param rentTypeName the value for common_rent_type.rent_type_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRentTypeName(String rentTypeName) {
        this.rentTypeName = rentTypeName == null ? null : rentTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_rent_type.rent_value
     *
     * @return the value of common_rent_type.rent_value
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getRentValue() {
        return rentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_rent_type.rent_value
     *
     * @param rentValue the value for common_rent_type.rent_value
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRentValue(Integer rentValue) {
        this.rentValue = rentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_rent_type.deleteflag
     *
     * @return the value of common_rent_type.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_rent_type.deleteflag
     *
     * @param deleteflag the value for common_rent_type.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}