package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class CommonHospitalTable extends CommonHospitalTableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.hospital_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.hospital_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String hospitalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.region_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.gps_location
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String gpsLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer sortindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastsync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_hospital_table.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.hospital_name
     *
     * @return the value of common_hospital_table.hospital_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.hospital_name
     *
     * @param hospitalName the value for common_hospital_table.hospital_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.hospital_type
     *
     * @return the value of common_hospital_table.hospital_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.hospital_type
     *
     * @param hospitalType the value for common_hospital_table.hospital_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setHospitalType(String hospitalType) {
        this.hospitalType = hospitalType == null ? null : hospitalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.city_id
     *
     * @return the value of common_hospital_table.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.city_id
     *
     * @param cityId the value for common_hospital_table.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.region_id
     *
     * @return the value of common_hospital_table.region_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.region_id
     *
     * @param regionId the value for common_hospital_table.region_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.gps_location
     *
     * @return the value of common_hospital_table.gps_location
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getGpsLocation() {
        return gpsLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.gps_location
     *
     * @param gpsLocation the value for common_hospital_table.gps_location
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setGpsLocation(String gpsLocation) {
        this.gpsLocation = gpsLocation == null ? null : gpsLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.sortindex
     *
     * @return the value of common_hospital_table.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getSortindex() {
        return sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.sortindex
     *
     * @param sortindex the value for common_hospital_table.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSortindex(Integer sortindex) {
        this.sortindex = sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.lastmodified
     *
     * @return the value of common_hospital_table.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.lastmodified
     *
     * @param lastmodified the value for common_hospital_table.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.lastsync
     *
     * @return the value of common_hospital_table.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastsync() {
        return lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.lastsync
     *
     * @param lastsync the value for common_hospital_table.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastsync(Date lastsync) {
        this.lastsync = lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_hospital_table.deleteflag
     *
     * @return the value of common_hospital_table.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_hospital_table.deleteflag
     *
     * @param deleteflag the value for common_hospital_table.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}