package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class CommonLoanRate extends CommonLoanRateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_loan_rate.rate_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer rateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_loan_rate.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_loan_rate.rate_val
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String rateVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_loan_rate.rate_date
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date rateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_loan_rate.rate_type
     *
     * @return the value of common_loan_rate.rate_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getRateType() {
        return rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_loan_rate.rate_type
     *
     * @param rateType the value for common_loan_rate.rate_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRateType(Integer rateType) {
        this.rateType = rateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_loan_rate.deleteflag
     *
     * @return the value of common_loan_rate.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_loan_rate.deleteflag
     *
     * @param deleteflag the value for common_loan_rate.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_loan_rate.rate_val
     *
     * @return the value of common_loan_rate.rate_val
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getRateVal() {
        return rateVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_loan_rate.rate_val
     *
     * @param rateVal the value for common_loan_rate.rate_val
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRateVal(String rateVal) {
        this.rateVal = rateVal == null ? null : rateVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_loan_rate.rate_date
     *
     * @return the value of common_loan_rate.rate_date
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getRateDate() {
        return rateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_loan_rate.rate_date
     *
     * @param rateDate the value for common_loan_rate.rate_date
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRateDate(Date rateDate) {
        this.rateDate = rateDate;
    }
}