package cn.hshb.web.biz.mybatis.model;

import java.util.Date;
import java.util.List;

public class CommonCountyTwo extends CommonCountyTwoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.county_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String countyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastsync;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.sort_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer sortFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_county_two.common_ids
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String commonIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.county_name
     *
     * @return the value of common_county_two.county_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.county_name
     *
     * @param countyName the value for common_county_two.county_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.city_id
     *
     * @return the value of common_county_two.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.city_id
     *
     * @param cityId the value for common_county_two.city_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.lastmodified
     *
     * @return the value of common_county_two.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.lastmodified
     *
     * @param lastmodified the value for common_county_two.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.lastsync
     *
     * @return the value of common_county_two.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastsync() {
        return lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.lastsync
     *
     * @param lastsync the value for common_county_two.lastsync
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastsync(Date lastsync) {
        this.lastsync = lastsync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.deleteflag
     *
     * @return the value of common_county_two.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.deleteflag
     *
     * @param deleteflag the value for common_county_two.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.sort_flag
     *
     * @return the value of common_county_two.sort_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getSortFlag() {
        return sortFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.sort_flag
     *
     * @param sortFlag the value for common_county_two.sort_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSortFlag(Integer sortFlag) {
        this.sortFlag = sortFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_county_two.common_ids
     *
     * @return the value of common_county_two.common_ids
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCommonIds() {
        return commonIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_county_two.common_ids
     *
     * @param commonIds the value for common_county_two.common_ids
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCommonIds(String commonIds) {
        this.commonIds = commonIds == null ? null : commonIds.trim();
    }
    
    /* 自定义 */
    
    /**
     * 区域对应的网站商圈
     */
    private List<CommonCbdWebsite> cbdWebsiteList;
    
    /**
     *对应网站商圈的websiteId
     */
    private List<Integer> cbdWebisteIdList;
    
	public List<Integer> getCbdWebisteIdList() {
		return cbdWebisteIdList;
	}

	public void setCbdWebisteIdList(List<Integer> cbdWebisteIdList) {
		this.cbdWebisteIdList = cbdWebisteIdList;
	}

	public List<CommonCbdWebsite> getCbdWebsiteList() {
		return cbdWebsiteList;
	}

	public void setCbdWebsiteList(List<CommonCbdWebsite> cbdWebsiteList) {
		this.cbdWebsiteList = cbdWebsiteList;
	}
    
}