package cn.hshb.web.biz.mybatis.model;

public class CommonLoanRateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column common_loan_rate.rate_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer rateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column common_loan_rate.rate_id
     *
     * @return the value of common_loan_rate.rate_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getRateId() {
        return rateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column common_loan_rate.rate_id
     *
     * @param rateId the value for common_loan_rate.rate_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRateId(Integer rateId) {
        this.rateId = rateId;
    }
}