package cn.hshb.web.biz.mybatis.model;

public class CountyForNewHouseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county_for_new_house.county_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer countyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county_for_new_house.county_id
     *
     * @return the value of county_for_new_house.county_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county_for_new_house.county_id
     *
     * @param countyId the value for county_for_new_house.county_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }
}