package cn.hshb.web.biz.mybatis.model;

public class DdhbSystemSetKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ddhb_system_set.set_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer setId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ddhb_system_set.set_id
     *
     * @return the value of ddhb_system_set.set_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ddhb_system_set.set_id
     *
     * @param setId the value for ddhb_system_set.set_id
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSetId(Integer setId) {
        this.setId = setId;
    }
}