package cn.hshb.web.biz.mybatis.model;

public class EfwDataRoleAuthority extends EfwDataRoleAuthorityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.DR_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer drId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.MODULE_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.ENTITY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.DATA_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.FIELD_VALUE
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String fieldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column efw_data_role_authority.FIELD_NAME
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String fieldName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.DR_ID
     *
     * @return the value of efw_data_role_authority.DR_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDrId() {
        return drId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.DR_ID
     *
     * @param drId the value for efw_data_role_authority.DR_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDrId(Integer drId) {
        this.drId = drId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.MODULE_ID
     *
     * @return the value of efw_data_role_authority.MODULE_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.MODULE_ID
     *
     * @param moduleId the value for efw_data_role_authority.MODULE_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.ENTITY_ID
     *
     * @return the value of efw_data_role_authority.ENTITY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.ENTITY_ID
     *
     * @param entityId the value for efw_data_role_authority.ENTITY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.DATA_ID
     *
     * @return the value of efw_data_role_authority.DATA_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.DATA_ID
     *
     * @param dataId the value for efw_data_role_authority.DATA_ID
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDataId(String dataId) {
        this.dataId = dataId == null ? null : dataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.FIELD_VALUE
     *
     * @return the value of efw_data_role_authority.FIELD_VALUE
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.FIELD_VALUE
     *
     * @param fieldValue the value for efw_data_role_authority.FIELD_VALUE
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue == null ? null : fieldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column efw_data_role_authority.FIELD_NAME
     *
     * @return the value of efw_data_role_authority.FIELD_NAME
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column efw_data_role_authority.FIELD_NAME
     *
     * @param fieldName the value for efw_data_role_authority.FIELD_NAME
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }
}