package cn.hshb.web.biz.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class EfwSourseEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public EfwSourseEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEntityIdIsNull() {
            addCriterion("ENTITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNotNull() {
            addCriterion("ENTITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntityIdEqualTo(Integer value) {
            addCriterion("ENTITY_ID =", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotEqualTo(Integer value) {
            addCriterion("ENTITY_ID <>", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThan(Integer value) {
            addCriterion("ENTITY_ID >", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENTITY_ID >=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThan(Integer value) {
            addCriterion("ENTITY_ID <", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThanOrEqualTo(Integer value) {
            addCriterion("ENTITY_ID <=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIn(List<Integer> values) {
            addCriterion("ENTITY_ID in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotIn(List<Integer> values) {
            addCriterion("ENTITY_ID not in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY_ID between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY_ID not between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityNameIsNull() {
            addCriterion("ENTITY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEntityNameIsNotNull() {
            addCriterion("ENTITY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEntityNameEqualTo(String value) {
            addCriterion("ENTITY_NAME =", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameNotEqualTo(String value) {
            addCriterion("ENTITY_NAME <>", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameGreaterThan(String value) {
            addCriterion("ENTITY_NAME >", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITY_NAME >=", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameLessThan(String value) {
            addCriterion("ENTITY_NAME <", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameLessThanOrEqualTo(String value) {
            addCriterion("ENTITY_NAME <=", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameLike(String value) {
            addCriterion("ENTITY_NAME like", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameNotLike(String value) {
            addCriterion("ENTITY_NAME not like", value, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameIn(List<String> values) {
            addCriterion("ENTITY_NAME in", values, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameNotIn(List<String> values) {
            addCriterion("ENTITY_NAME not in", values, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameBetween(String value1, String value2) {
            addCriterion("ENTITY_NAME between", value1, value2, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityNameNotBetween(String value1, String value2) {
            addCriterion("ENTITY_NAME not between", value1, value2, "entityName");
            return (Criteria) this;
        }

        public Criteria andEntityClassIsNull() {
            addCriterion("ENTITY_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andEntityClassIsNotNull() {
            addCriterion("ENTITY_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andEntityClassEqualTo(String value) {
            addCriterion("ENTITY_CLASS =", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassNotEqualTo(String value) {
            addCriterion("ENTITY_CLASS <>", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassGreaterThan(String value) {
            addCriterion("ENTITY_CLASS >", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITY_CLASS >=", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassLessThan(String value) {
            addCriterion("ENTITY_CLASS <", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassLessThanOrEqualTo(String value) {
            addCriterion("ENTITY_CLASS <=", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassLike(String value) {
            addCriterion("ENTITY_CLASS like", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassNotLike(String value) {
            addCriterion("ENTITY_CLASS not like", value, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassIn(List<String> values) {
            addCriterion("ENTITY_CLASS in", values, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassNotIn(List<String> values) {
            addCriterion("ENTITY_CLASS not in", values, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassBetween(String value1, String value2) {
            addCriterion("ENTITY_CLASS between", value1, value2, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityClassNotBetween(String value1, String value2) {
            addCriterion("ENTITY_CLASS not between", value1, value2, "entityClass");
            return (Criteria) this;
        }

        public Criteria andEntityFieldIsNull() {
            addCriterion("ENTITY_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andEntityFieldIsNotNull() {
            addCriterion("ENTITY_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andEntityFieldEqualTo(String value) {
            addCriterion("ENTITY_FIELD =", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldNotEqualTo(String value) {
            addCriterion("ENTITY_FIELD <>", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldGreaterThan(String value) {
            addCriterion("ENTITY_FIELD >", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITY_FIELD >=", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldLessThan(String value) {
            addCriterion("ENTITY_FIELD <", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldLessThanOrEqualTo(String value) {
            addCriterion("ENTITY_FIELD <=", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldLike(String value) {
            addCriterion("ENTITY_FIELD like", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldNotLike(String value) {
            addCriterion("ENTITY_FIELD not like", value, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldIn(List<String> values) {
            addCriterion("ENTITY_FIELD in", values, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldNotIn(List<String> values) {
            addCriterion("ENTITY_FIELD not in", values, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldBetween(String value1, String value2) {
            addCriterion("ENTITY_FIELD between", value1, value2, "entityField");
            return (Criteria) this;
        }

        public Criteria andEntityFieldNotBetween(String value1, String value2) {
            addCriterion("ENTITY_FIELD not between", value1, value2, "entityField");
            return (Criteria) this;
        }

        public Criteria andQueryUrlIsNull() {
            addCriterion("QUERY_URL is null");
            return (Criteria) this;
        }

        public Criteria andQueryUrlIsNotNull() {
            addCriterion("QUERY_URL is not null");
            return (Criteria) this;
        }

        public Criteria andQueryUrlEqualTo(String value) {
            addCriterion("QUERY_URL =", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlNotEqualTo(String value) {
            addCriterion("QUERY_URL <>", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlGreaterThan(String value) {
            addCriterion("QUERY_URL >", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_URL >=", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlLessThan(String value) {
            addCriterion("QUERY_URL <", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlLessThanOrEqualTo(String value) {
            addCriterion("QUERY_URL <=", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlLike(String value) {
            addCriterion("QUERY_URL like", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlNotLike(String value) {
            addCriterion("QUERY_URL not like", value, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlIn(List<String> values) {
            addCriterion("QUERY_URL in", values, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlNotIn(List<String> values) {
            addCriterion("QUERY_URL not in", values, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlBetween(String value1, String value2) {
            addCriterion("QUERY_URL between", value1, value2, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryUrlNotBetween(String value1, String value2) {
            addCriterion("QUERY_URL not between", value1, value2, "queryUrl");
            return (Criteria) this;
        }

        public Criteria andQueryParamIsNull() {
            addCriterion("QUERY_PARAM is null");
            return (Criteria) this;
        }

        public Criteria andQueryParamIsNotNull() {
            addCriterion("QUERY_PARAM is not null");
            return (Criteria) this;
        }

        public Criteria andQueryParamEqualTo(String value) {
            addCriterion("QUERY_PARAM =", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamNotEqualTo(String value) {
            addCriterion("QUERY_PARAM <>", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamGreaterThan(String value) {
            addCriterion("QUERY_PARAM >", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamGreaterThanOrEqualTo(String value) {
            addCriterion("QUERY_PARAM >=", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamLessThan(String value) {
            addCriterion("QUERY_PARAM <", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamLessThanOrEqualTo(String value) {
            addCriterion("QUERY_PARAM <=", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamLike(String value) {
            addCriterion("QUERY_PARAM like", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamNotLike(String value) {
            addCriterion("QUERY_PARAM not like", value, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamIn(List<String> values) {
            addCriterion("QUERY_PARAM in", values, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamNotIn(List<String> values) {
            addCriterion("QUERY_PARAM not in", values, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamBetween(String value1, String value2) {
            addCriterion("QUERY_PARAM between", value1, value2, "queryParam");
            return (Criteria) this;
        }

        public Criteria andQueryParamNotBetween(String value1, String value2) {
            addCriterion("QUERY_PARAM not between", value1, value2, "queryParam");
            return (Criteria) this;
        }

        public Criteria andEntityAliasIsNull() {
            addCriterion("ENTITY_ALIAS is null");
            return (Criteria) this;
        }

        public Criteria andEntityAliasIsNotNull() {
            addCriterion("ENTITY_ALIAS is not null");
            return (Criteria) this;
        }

        public Criteria andEntityAliasEqualTo(String value) {
            addCriterion("ENTITY_ALIAS =", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasNotEqualTo(String value) {
            addCriterion("ENTITY_ALIAS <>", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasGreaterThan(String value) {
            addCriterion("ENTITY_ALIAS >", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITY_ALIAS >=", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasLessThan(String value) {
            addCriterion("ENTITY_ALIAS <", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasLessThanOrEqualTo(String value) {
            addCriterion("ENTITY_ALIAS <=", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasLike(String value) {
            addCriterion("ENTITY_ALIAS like", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasNotLike(String value) {
            addCriterion("ENTITY_ALIAS not like", value, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasIn(List<String> values) {
            addCriterion("ENTITY_ALIAS in", values, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasNotIn(List<String> values) {
            addCriterion("ENTITY_ALIAS not in", values, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasBetween(String value1, String value2) {
            addCriterion("ENTITY_ALIAS between", value1, value2, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andEntityAliasNotBetween(String value1, String value2) {
            addCriterion("ENTITY_ALIAS not between", value1, value2, "entityAlias");
            return (Criteria) this;
        }

        public Criteria andOutputKeyIsNull() {
            addCriterion("OUTPUT_KEY is null");
            return (Criteria) this;
        }

        public Criteria andOutputKeyIsNotNull() {
            addCriterion("OUTPUT_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andOutputKeyEqualTo(String value) {
            addCriterion("OUTPUT_KEY =", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyNotEqualTo(String value) {
            addCriterion("OUTPUT_KEY <>", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyGreaterThan(String value) {
            addCriterion("OUTPUT_KEY >", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyGreaterThanOrEqualTo(String value) {
            addCriterion("OUTPUT_KEY >=", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyLessThan(String value) {
            addCriterion("OUTPUT_KEY <", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyLessThanOrEqualTo(String value) {
            addCriterion("OUTPUT_KEY <=", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyLike(String value) {
            addCriterion("OUTPUT_KEY like", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyNotLike(String value) {
            addCriterion("OUTPUT_KEY not like", value, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyIn(List<String> values) {
            addCriterion("OUTPUT_KEY in", values, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyNotIn(List<String> values) {
            addCriterion("OUTPUT_KEY not in", values, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyBetween(String value1, String value2) {
            addCriterion("OUTPUT_KEY between", value1, value2, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputKeyNotBetween(String value1, String value2) {
            addCriterion("OUTPUT_KEY not between", value1, value2, "outputKey");
            return (Criteria) this;
        }

        public Criteria andOutputTitleIsNull() {
            addCriterion("OUTPUT_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andOutputTitleIsNotNull() {
            addCriterion("OUTPUT_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andOutputTitleEqualTo(String value) {
            addCriterion("OUTPUT_TITLE =", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleNotEqualTo(String value) {
            addCriterion("OUTPUT_TITLE <>", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleGreaterThan(String value) {
            addCriterion("OUTPUT_TITLE >", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleGreaterThanOrEqualTo(String value) {
            addCriterion("OUTPUT_TITLE >=", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleLessThan(String value) {
            addCriterion("OUTPUT_TITLE <", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleLessThanOrEqualTo(String value) {
            addCriterion("OUTPUT_TITLE <=", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleLike(String value) {
            addCriterion("OUTPUT_TITLE like", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleNotLike(String value) {
            addCriterion("OUTPUT_TITLE not like", value, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleIn(List<String> values) {
            addCriterion("OUTPUT_TITLE in", values, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleNotIn(List<String> values) {
            addCriterion("OUTPUT_TITLE not in", values, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleBetween(String value1, String value2) {
            addCriterion("OUTPUT_TITLE between", value1, value2, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputTitleNotBetween(String value1, String value2) {
            addCriterion("OUTPUT_TITLE not between", value1, value2, "outputTitle");
            return (Criteria) this;
        }

        public Criteria andOutputClassIsNull() {
            addCriterion("OUTPUT_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andOutputClassIsNotNull() {
            addCriterion("OUTPUT_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andOutputClassEqualTo(String value) {
            addCriterion("OUTPUT_CLASS =", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassNotEqualTo(String value) {
            addCriterion("OUTPUT_CLASS <>", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassGreaterThan(String value) {
            addCriterion("OUTPUT_CLASS >", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassGreaterThanOrEqualTo(String value) {
            addCriterion("OUTPUT_CLASS >=", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassLessThan(String value) {
            addCriterion("OUTPUT_CLASS <", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassLessThanOrEqualTo(String value) {
            addCriterion("OUTPUT_CLASS <=", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassLike(String value) {
            addCriterion("OUTPUT_CLASS like", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassNotLike(String value) {
            addCriterion("OUTPUT_CLASS not like", value, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassIn(List<String> values) {
            addCriterion("OUTPUT_CLASS in", values, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassNotIn(List<String> values) {
            addCriterion("OUTPUT_CLASS not in", values, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassBetween(String value1, String value2) {
            addCriterion("OUTPUT_CLASS between", value1, value2, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputClassNotBetween(String value1, String value2) {
            addCriterion("OUTPUT_CLASS not between", value1, value2, "outputClass");
            return (Criteria) this;
        }

        public Criteria andOutputValueIsNull() {
            addCriterion("OUTPUT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andOutputValueIsNotNull() {
            addCriterion("OUTPUT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andOutputValueEqualTo(String value) {
            addCriterion("OUTPUT_VALUE =", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueNotEqualTo(String value) {
            addCriterion("OUTPUT_VALUE <>", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueGreaterThan(String value) {
            addCriterion("OUTPUT_VALUE >", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueGreaterThanOrEqualTo(String value) {
            addCriterion("OUTPUT_VALUE >=", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueLessThan(String value) {
            addCriterion("OUTPUT_VALUE <", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueLessThanOrEqualTo(String value) {
            addCriterion("OUTPUT_VALUE <=", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueLike(String value) {
            addCriterion("OUTPUT_VALUE like", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueNotLike(String value) {
            addCriterion("OUTPUT_VALUE not like", value, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueIn(List<String> values) {
            addCriterion("OUTPUT_VALUE in", values, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueNotIn(List<String> values) {
            addCriterion("OUTPUT_VALUE not in", values, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueBetween(String value1, String value2) {
            addCriterion("OUTPUT_VALUE between", value1, value2, "outputValue");
            return (Criteria) this;
        }

        public Criteria andOutputValueNotBetween(String value1, String value2) {
            addCriterion("OUTPUT_VALUE not between", value1, value2, "outputValue");
            return (Criteria) this;
        }

        public Criteria andNotNullIsNull() {
            addCriterion("NOT_NULL is null");
            return (Criteria) this;
        }

        public Criteria andNotNullIsNotNull() {
            addCriterion("NOT_NULL is not null");
            return (Criteria) this;
        }

        public Criteria andNotNullEqualTo(Integer value) {
            addCriterion("NOT_NULL =", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullNotEqualTo(Integer value) {
            addCriterion("NOT_NULL <>", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullGreaterThan(Integer value) {
            addCriterion("NOT_NULL >", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullGreaterThanOrEqualTo(Integer value) {
            addCriterion("NOT_NULL >=", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullLessThan(Integer value) {
            addCriterion("NOT_NULL <", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullLessThanOrEqualTo(Integer value) {
            addCriterion("NOT_NULL <=", value, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullIn(List<Integer> values) {
            addCriterion("NOT_NULL in", values, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullNotIn(List<Integer> values) {
            addCriterion("NOT_NULL not in", values, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullBetween(Integer value1, Integer value2) {
            addCriterion("NOT_NULL between", value1, value2, "notNull");
            return (Criteria) this;
        }

        public Criteria andNotNullNotBetween(Integer value1, Integer value2) {
            addCriterion("NOT_NULL not between", value1, value2, "notNull");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}