package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class EntrustBuyhouse extends EntrustBuyhouseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer locationRequirementFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String cbdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String communityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.maxShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer maxshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.minShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer minshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer shi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer ting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer wei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer minprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer maxprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String otherRequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.otherContect
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String othercontect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer synchronizedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date synchronizedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.location_requirement_flag
     *
     * @return the value of entrust_buyhouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getLocationRequirementFlag() {
        return locationRequirementFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.location_requirement_flag
     *
     * @param locationRequirementFlag the value for entrust_buyhouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLocationRequirementFlag(Integer locationRequirementFlag) {
        this.locationRequirementFlag = locationRequirementFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.cbd_no
     *
     * @return the value of entrust_buyhouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCbdNo() {
        return cbdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.cbd_no
     *
     * @param cbdNo the value for entrust_buyhouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCbdNo(String cbdNo) {
        this.cbdNo = cbdNo == null ? null : cbdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.community_no
     *
     * @return the value of entrust_buyhouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCommunityNo() {
        return communityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.community_no
     *
     * @param communityNo the value for entrust_buyhouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCommunityNo(String communityNo) {
        this.communityNo = communityNo == null ? null : communityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.community_name
     *
     * @return the value of entrust_buyhouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.community_name
     *
     * @param communityName the value for entrust_buyhouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.maxShi
     *
     * @return the value of entrust_buyhouse.maxShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMaxshi() {
        return maxshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.maxShi
     *
     * @param maxshi the value for entrust_buyhouse.maxShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMaxshi(Integer maxshi) {
        this.maxshi = maxshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.minShi
     *
     * @return the value of entrust_buyhouse.minShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMinshi() {
        return minshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.minShi
     *
     * @param minshi the value for entrust_buyhouse.minShi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMinshi(Integer minshi) {
        this.minshi = minshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.shi
     *
     * @return the value of entrust_buyhouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.shi
     *
     * @param shi the value for entrust_buyhouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setShi(Integer shi) {
        this.shi = shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.ting
     *
     * @return the value of entrust_buyhouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getTing() {
        return ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.ting
     *
     * @param ting the value for entrust_buyhouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setTing(Integer ting) {
        this.ting = ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.wei
     *
     * @return the value of entrust_buyhouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getWei() {
        return wei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.wei
     *
     * @param wei the value for entrust_buyhouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setWei(Integer wei) {
        this.wei = wei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.minprice
     *
     * @return the value of entrust_buyhouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMinprice() {
        return minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.minprice
     *
     * @param minprice the value for entrust_buyhouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMinprice(Integer minprice) {
        this.minprice = minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.maxprice
     *
     * @return the value of entrust_buyhouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMaxprice() {
        return maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.maxprice
     *
     * @param maxprice the value for entrust_buyhouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMaxprice(Integer maxprice) {
        this.maxprice = maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.other_requirement
     *
     * @return the value of entrust_buyhouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getOtherRequirement() {
        return otherRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.other_requirement
     *
     * @param otherRequirement the value for entrust_buyhouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setOtherRequirement(String otherRequirement) {
        this.otherRequirement = otherRequirement == null ? null : otherRequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.user_no
     *
     * @return the value of entrust_buyhouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.user_no
     *
     * @param userNo the value for entrust_buyhouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.name
     *
     * @return the value of entrust_buyhouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.name
     *
     * @param name the value for entrust_buyhouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.gender
     *
     * @return the value of entrust_buyhouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.gender
     *
     * @param gender the value for entrust_buyhouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.telephone
     *
     * @return the value of entrust_buyhouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.telephone
     *
     * @param telephone the value for entrust_buyhouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.otherContect
     *
     * @return the value of entrust_buyhouse.otherContect
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getOthercontect() {
        return othercontect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.otherContect
     *
     * @param othercontect the value for entrust_buyhouse.otherContect
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setOthercontect(String othercontect) {
        this.othercontect = othercontect == null ? null : othercontect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.synchronized_flag
     *
     * @return the value of entrust_buyhouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getSynchronizedFlag() {
        return synchronizedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.synchronized_flag
     *
     * @param synchronizedFlag the value for entrust_buyhouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSynchronizedFlag(Integer synchronizedFlag) {
        this.synchronizedFlag = synchronizedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.lastmodified
     *
     * @return the value of entrust_buyhouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.lastmodified
     *
     * @param lastmodified the value for entrust_buyhouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.synchronized_time
     *
     * @return the value of entrust_buyhouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getSynchronizedTime() {
        return synchronizedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.synchronized_time
     *
     * @param synchronizedTime the value for entrust_buyhouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSynchronizedTime(Date synchronizedTime) {
        this.synchronizedTime = synchronizedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.deleteflag
     *
     * @return the value of entrust_buyhouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.deleteflag
     *
     * @param deleteflag the value for entrust_buyhouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}