package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class EntrustRenthouse extends EntrustRenthouseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer locationRequirementFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String cbdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String communityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer communityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer maxprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer minprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.maxshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer maxshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.minshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer minshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer shi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer ting;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer wei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.rent_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String rentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String liveFacility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String otherRequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.otherContact
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private String othercontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer synchronizedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Date synchronizedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_renthouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.location_requirement_flag
     *
     * @return the value of entrust_renthouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getLocationRequirementFlag() {
        return locationRequirementFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.location_requirement_flag
     *
     * @param locationRequirementFlag the value for entrust_renthouse.location_requirement_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLocationRequirementFlag(Integer locationRequirementFlag) {
        this.locationRequirementFlag = locationRequirementFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.cbd_no
     *
     * @return the value of entrust_renthouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCbdNo() {
        return cbdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.cbd_no
     *
     * @param cbdNo the value for entrust_renthouse.cbd_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCbdNo(String cbdNo) {
        this.cbdNo = cbdNo == null ? null : cbdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.community_name
     *
     * @return the value of entrust_renthouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.community_name
     *
     * @param communityName the value for entrust_renthouse.community_name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName == null ? null : communityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.community_no
     *
     * @return the value of entrust_renthouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getCommunityNo() {
        return communityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.community_no
     *
     * @param communityNo the value for entrust_renthouse.community_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setCommunityNo(Integer communityNo) {
        this.communityNo = communityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.maxprice
     *
     * @return the value of entrust_renthouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMaxprice() {
        return maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.maxprice
     *
     * @param maxprice the value for entrust_renthouse.maxprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMaxprice(Integer maxprice) {
        this.maxprice = maxprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.minprice
     *
     * @return the value of entrust_renthouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMinprice() {
        return minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.minprice
     *
     * @param minprice the value for entrust_renthouse.minprice
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMinprice(Integer minprice) {
        this.minprice = minprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.maxshi
     *
     * @return the value of entrust_renthouse.maxshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMaxshi() {
        return maxshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.maxshi
     *
     * @param maxshi the value for entrust_renthouse.maxshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMaxshi(Integer maxshi) {
        this.maxshi = maxshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.minshi
     *
     * @return the value of entrust_renthouse.minshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getMinshi() {
        return minshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.minshi
     *
     * @param minshi the value for entrust_renthouse.minshi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setMinshi(Integer minshi) {
        this.minshi = minshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.shi
     *
     * @return the value of entrust_renthouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getShi() {
        return shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.shi
     *
     * @param shi the value for entrust_renthouse.shi
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setShi(Integer shi) {
        this.shi = shi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.ting
     *
     * @return the value of entrust_renthouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getTing() {
        return ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.ting
     *
     * @param ting the value for entrust_renthouse.ting
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setTing(Integer ting) {
        this.ting = ting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.wei
     *
     * @return the value of entrust_renthouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getWei() {
        return wei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.wei
     *
     * @param wei the value for entrust_renthouse.wei
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setWei(Integer wei) {
        this.wei = wei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.rent_type
     *
     * @return the value of entrust_renthouse.rent_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getRentType() {
        return rentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.rent_type
     *
     * @param rentType the value for entrust_renthouse.rent_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setRentType(String rentType) {
        this.rentType = rentType == null ? null : rentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.live_facility
     *
     * @return the value of entrust_renthouse.live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getLiveFacility() {
        return liveFacility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.live_facility
     *
     * @param liveFacility the value for entrust_renthouse.live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLiveFacility(String liveFacility) {
        this.liveFacility = liveFacility == null ? null : liveFacility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.other_requirement
     *
     * @return the value of entrust_renthouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getOtherRequirement() {
        return otherRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.other_requirement
     *
     * @param otherRequirement the value for entrust_renthouse.other_requirement
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setOtherRequirement(String otherRequirement) {
        this.otherRequirement = otherRequirement == null ? null : otherRequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.user_no
     *
     * @return the value of entrust_renthouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.user_no
     *
     * @param userNo the value for entrust_renthouse.user_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setUserNo(Integer userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.name
     *
     * @return the value of entrust_renthouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.name
     *
     * @param name the value for entrust_renthouse.name
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.gender
     *
     * @return the value of entrust_renthouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.gender
     *
     * @param gender the value for entrust_renthouse.gender
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.telephone
     *
     * @return the value of entrust_renthouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.telephone
     *
     * @param telephone the value for entrust_renthouse.telephone
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.otherContact
     *
     * @return the value of entrust_renthouse.otherContact
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public String getOthercontact() {
        return othercontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.otherContact
     *
     * @param othercontact the value for entrust_renthouse.otherContact
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setOthercontact(String othercontact) {
        this.othercontact = othercontact == null ? null : othercontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.synchronized_flag
     *
     * @return the value of entrust_renthouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getSynchronizedFlag() {
        return synchronizedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.synchronized_flag
     *
     * @param synchronizedFlag the value for entrust_renthouse.synchronized_flag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSynchronizedFlag(Integer synchronizedFlag) {
        this.synchronizedFlag = synchronizedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.lastmodified
     *
     * @return the value of entrust_renthouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.lastmodified
     *
     * @param lastmodified the value for entrust_renthouse.lastmodified
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.synchronized_time
     *
     * @return the value of entrust_renthouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Date getSynchronizedTime() {
        return synchronizedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.synchronized_time
     *
     * @param synchronizedTime the value for entrust_renthouse.synchronized_time
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setSynchronizedTime(Date synchronizedTime) {
        this.synchronizedTime = synchronizedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_renthouse.deleteflag
     *
     * @return the value of entrust_renthouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_renthouse.deleteflag
     *
     * @param deleteflag the value for entrust_renthouse.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}