package cn.hshb.web.biz.mybatis.model;

public class EntrustBuyhouseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_buyhouse.buy_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    private Integer buyNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_buyhouse.buy_no
     *
     * @return the value of entrust_buyhouse.buy_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public Integer getBuyNo() {
        return buyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_buyhouse.buy_no
     *
     * @param buyNo the value for entrust_buyhouse.buy_no
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    public void setBuyNo(Integer buyNo) {
        this.buyNo = buyNo;
    }
}