package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class FrendLink extends FrendLinkKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.picture_url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.hover_comment
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String hoverComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.display_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer displayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.name
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.enable_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer enableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.start_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.end_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer sortindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column frend_link.delete_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.picture_url
     *
     * @return the value of frend_link.picture_url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.picture_url
     *
     * @param pictureUrl the value for frend_link.picture_url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.hover_comment
     *
     * @return the value of frend_link.hover_comment
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getHoverComment() {
        return hoverComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.hover_comment
     *
     * @param hoverComment the value for frend_link.hover_comment
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setHoverComment(String hoverComment) {
        this.hoverComment = hoverComment == null ? null : hoverComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.display_type
     *
     * @return the value of frend_link.display_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getDisplayType() {
        return displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.display_type
     *
     * @param displayType the value for frend_link.display_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setDisplayType(Integer displayType) {
        this.displayType = displayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.name
     *
     * @return the value of frend_link.name
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.name
     *
     * @param name the value for frend_link.name
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.url
     *
     * @return the value of frend_link.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.url
     *
     * @param url the value for frend_link.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.enable_type
     *
     * @return the value of frend_link.enable_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getEnableType() {
        return enableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.enable_type
     *
     * @param enableType the value for frend_link.enable_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setEnableType(Integer enableType) {
        this.enableType = enableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.start_date
     *
     * @return the value of frend_link.start_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.start_date
     *
     * @param startDate the value for frend_link.start_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.end_date
     *
     * @return the value of frend_link.end_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.end_date
     *
     * @param endDate the value for frend_link.end_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.sortindex
     *
     * @return the value of frend_link.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getSortindex() {
        return sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.sortindex
     *
     * @param sortindex the value for frend_link.sortindex
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setSortindex(Integer sortindex) {
        this.sortindex = sortindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column frend_link.delete_flag
     *
     * @return the value of frend_link.delete_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column frend_link.delete_flag
     *
     * @param deleteFlag the value for frend_link.delete_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}