package cn.hshb.web.biz.mybatis.model;

public class FwAccountDutyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_account_duty.ACC_DUTY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer accDutyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_account_duty.ACC_DUTY_ID
     *
     * @return the value of fw_account_duty.ACC_DUTY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getAccDutyId() {
        return accDutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_account_duty.ACC_DUTY_ID
     *
     * @param accDutyId the value for fw_account_duty.ACC_DUTY_ID
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setAccDutyId(Integer accDutyId) {
        this.accDutyId = accDutyId;
    }
}