package cn.hshb.web.biz.mybatis.model;

public class FwPropertiesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fw_properties.properties_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer propertiesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fw_properties.properties_id
     *
     * @return the value of fw_properties.properties_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getPropertiesId() {
        return propertiesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fw_properties.properties_id
     *
     * @param propertiesId the value for fw_properties.properties_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setPropertiesId(Integer propertiesId) {
        this.propertiesId = propertiesId;
    }
}