package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class HouseReduceNotice extends HouseReduceNoticeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.create_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.current_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Float currentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.notice_email
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String noticeEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.notice_phone
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String noticePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.house_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String houseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.house_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.broker_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String brokerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.house_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.email_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer emailFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.phone_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer phoneFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.house_title
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String houseTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.email_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer emailDone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_reduce_notice.sms_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer smsDone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.member_id
     *
     * @return the value of house_reduce_notice.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.member_id
     *
     * @param memberId the value for house_reduce_notice.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.create_time
     *
     * @return the value of house_reduce_notice.create_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.create_time
     *
     * @param createTime the value for house_reduce_notice.create_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.current_price
     *
     * @return the value of house_reduce_notice.current_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Float getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.current_price
     *
     * @param currentPrice the value for house_reduce_notice.current_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setCurrentPrice(Float currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.deleteflag
     *
     * @return the value of house_reduce_notice.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.deleteflag
     *
     * @param deleteflag the value for house_reduce_notice.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.notice_email
     *
     * @return the value of house_reduce_notice.notice_email
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getNoticeEmail() {
        return noticeEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.notice_email
     *
     * @param noticeEmail the value for house_reduce_notice.notice_email
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setNoticeEmail(String noticeEmail) {
        this.noticeEmail = noticeEmail == null ? null : noticeEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.notice_phone
     *
     * @return the value of house_reduce_notice.notice_phone
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getNoticePhone() {
        return noticePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.notice_phone
     *
     * @param noticePhone the value for house_reduce_notice.notice_phone
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setNoticePhone(String noticePhone) {
        this.noticePhone = noticePhone == null ? null : noticePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.house_no
     *
     * @return the value of house_reduce_notice.house_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getHouseNo() {
        return houseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.house_no
     *
     * @param houseNo the value for house_reduce_notice.house_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setHouseNo(String houseNo) {
        this.houseNo = houseNo == null ? null : houseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.house_type
     *
     * @return the value of house_reduce_notice.house_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.house_type
     *
     * @param houseType the value for house_reduce_notice.house_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setHouseType(Integer houseType) {
        this.houseType = houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.broker_id
     *
     * @return the value of house_reduce_notice.broker_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getBrokerId() {
        return brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.broker_id
     *
     * @param brokerId the value for house_reduce_notice.broker_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setBrokerId(String brokerId) {
        this.brokerId = brokerId == null ? null : brokerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.house_id
     *
     * @return the value of house_reduce_notice.house_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.house_id
     *
     * @param houseId the value for house_reduce_notice.house_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.email_flag
     *
     * @return the value of house_reduce_notice.email_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getEmailFlag() {
        return emailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.email_flag
     *
     * @param emailFlag the value for house_reduce_notice.email_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setEmailFlag(Integer emailFlag) {
        this.emailFlag = emailFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.phone_flag
     *
     * @return the value of house_reduce_notice.phone_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getPhoneFlag() {
        return phoneFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.phone_flag
     *
     * @param phoneFlag the value for house_reduce_notice.phone_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setPhoneFlag(Integer phoneFlag) {
        this.phoneFlag = phoneFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.house_title
     *
     * @return the value of house_reduce_notice.house_title
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getHouseTitle() {
        return houseTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.house_title
     *
     * @param houseTitle the value for house_reduce_notice.house_title
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setHouseTitle(String houseTitle) {
        this.houseTitle = houseTitle == null ? null : houseTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.email_done
     *
     * @return the value of house_reduce_notice.email_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getEmailDone() {
        return emailDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.email_done
     *
     * @param emailDone the value for house_reduce_notice.email_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setEmailDone(Integer emailDone) {
        this.emailDone = emailDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_reduce_notice.sms_done
     *
     * @return the value of house_reduce_notice.sms_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getSmsDone() {
        return smsDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_reduce_notice.sms_done
     *
     * @param smsDone the value for house_reduce_notice.sms_done
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setSmsDone(Integer smsDone) {
        this.smsDone = smsDone;
    }
    
    /*******************以下自定义属性*************/
	private HouseSecondHandHouse houseSecond;
	private HouseRentHouse houseRent;
	private BBroker broker;
	
	/**
	 * 价格变动趋势标志，-1：上涨,0:持平，1：下跌 
	 */
	private int priceFlag;

	
	public HouseSecondHandHouse getHouseSecond() {
		return houseSecond;
	}

	public void setHouseSecond(HouseSecondHandHouse houseSecond) {
		this.houseSecond = houseSecond;
	}

	public HouseRentHouse getHouseRent() {
		return houseRent;
	}

	public void setHouseRent(HouseRentHouse houseRent) {
		this.houseRent = houseRent;
	}

	public BBroker getBroker() {
		return broker;
	}

	public void setBroker(BBroker broker) {
		this.broker = broker;
	}

	public int getPriceFlag() {
		return priceFlag;
	}

	public void setPriceFlag(int priceFlag) {
		this.priceFlag = priceFlag;
	}
	
}