package cn.hshb.web.biz.mybatis.model;

public class HouseNewBrowseAnalyseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_new_browse_analyse.analyse_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String analyseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_new_browse_analyse.analyse_id
     *
     * @return the value of house_new_browse_analyse.analyse_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getAnalyseId() {
        return analyseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_new_browse_analyse.analyse_id
     *
     * @param analyseId the value for house_new_browse_analyse.analyse_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setAnalyseId(String analyseId) {
        this.analyseId = analyseId == null ? null : analyseId.trim();
    }
}