package cn.hshb.web.biz.mybatis.model;

public class HouseNewhouseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_newhouse.newhouse_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer newhouseNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_newhouse.newhouse_no
     *
     * @return the value of house_newhouse.newhouse_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getNewhouseNo() {
        return newhouseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_newhouse.newhouse_no
     *
     * @param newhouseNo the value for house_newhouse.newhouse_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setNewhouseNo(Integer newhouseNo) {
        this.newhouseNo = newhouseNo;
    }
}