package cn.hshb.web.biz.mybatis.model;

public class HouseSecondPriceTrendKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column house_second_price_trend.trent_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer trentNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column house_second_price_trend.trent_no
     *
     * @return the value of house_second_price_trend.trent_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getTrentNo() {
        return trentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column house_second_price_trend.trent_no
     *
     * @param trentNo the value for house_second_price_trend.trent_no
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setTrentNo(Integer trentNo) {
        this.trentNo = trentNo;
    }
}