package cn.hshb.web.biz.mybatis.model;

public class MailSendInfoWithBLOBs extends MailSendInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mail_send_info.mail_content
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_send_info.mail_content
     *
     * @return the value of mail_send_info.mail_content
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_send_info.mail_content
     *
     * @param mailContent the value for mail_send_info.mail_content
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent == null ? null : mailContent.trim();
    }
}