package cn.hshb.web.biz.mybatis.model;

public class MemberBespeakKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_bespeak.bespeak_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer bespeakId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_bespeak.bespeak_id
     *
     * @return the value of member_bespeak.bespeak_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getBespeakId() {
        return bespeakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_bespeak.bespeak_id
     *
     * @param bespeakId the value for member_bespeak.bespeak_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setBespeakId(Integer bespeakId) {
        this.bespeakId = bespeakId;
    }
}