package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class MemberSavedSearchcontent extends MemberSavedSearchcontentKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.saved_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String savedField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.create_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_saved_searchcontent.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.member_id
     *
     * @return the value of member_saved_searchcontent.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.member_id
     *
     * @param memberId the value for member_saved_searchcontent.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.type
     *
     * @return the value of member_saved_searchcontent.type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.type
     *
     * @param type the value for member_saved_searchcontent.type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.url
     *
     * @return the value of member_saved_searchcontent.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.url
     *
     * @param url the value for member_saved_searchcontent.url
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.saved_field
     *
     * @return the value of member_saved_searchcontent.saved_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getSavedField() {
        return savedField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.saved_field
     *
     * @param savedField the value for member_saved_searchcontent.saved_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setSavedField(String savedField) {
        this.savedField = savedField == null ? null : savedField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.create_date
     *
     * @return the value of member_saved_searchcontent.create_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.create_date
     *
     * @param createDate the value for member_saved_searchcontent.create_date
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_saved_searchcontent.deleteflag
     *
     * @return the value of member_saved_searchcontent.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_saved_searchcontent.deleteflag
     *
     * @param deleteflag the value for member_saved_searchcontent.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
}