package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

import com.huatek.hbwebsite.common.entity.Community;
import com.huatek.hbwebsite.house.entity.HouseRent;
import com.huatek.hbwebsite.house.entity.HouseSecond;

public class MemberBrowseHistory extends MemberBrowseHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.object_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.object_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String objectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.modified_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_browse_history.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer deleteflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.member_id
     *
     * @return the value of member_browse_history.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.member_id
     *
     * @param memberId the value for member_browse_history.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.object_type
     *
     * @return the value of member_browse_history.object_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.object_type
     *
     * @param objectType the value for member_browse_history.object_type
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.object_id
     *
     * @return the value of member_browse_history.object_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.object_id
     *
     * @param objectId the value for member_browse_history.object_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId == null ? null : objectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.created_time
     *
     * @return the value of member_browse_history.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.created_time
     *
     * @param createdTime the value for member_browse_history.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.modified_time
     *
     * @return the value of member_browse_history.modified_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.modified_time
     *
     * @param modifiedTime the value for member_browse_history.modified_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_browse_history.deleteflag
     *
     * @return the value of member_browse_history.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_browse_history.deleteflag
     *
     * @param deleteflag the value for member_browse_history.deleteflag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setDeleteflag(Integer deleteflag) {
        this.deleteflag = deleteflag;
    }
    
    
    /************************以下自定义属性**************************/
    /**
     * 浏览的二手房源
     */
	private HouseSecondHandHouse secondHouse;
	
	/**
	 * 浏览的租赁房源
	 */
	private HouseRentHouse rentHouse;
	
	/**
	 * 浏览的小区
	 */
	private HouseCommunity community;

	public HouseSecondHandHouse getSecondHouse() {
		return secondHouse;
	}

	public void setSecondHouse(HouseSecondHandHouse secondHouse) {
		this.secondHouse = secondHouse;
	}

	public HouseRentHouse getRentHouse() {
		return rentHouse;
	}

	public void setRentHouse(HouseRentHouse rentHouse) {
		this.rentHouse = rentHouse;
	}

	public HouseCommunity getCommunity() {
		return community;
	}

	public void setCommunity(HouseCommunity community) {
		this.community = community;
	}
	
	
}