package cn.hshb.web.biz.mybatis.model;

public class NewsTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_type.type_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_type.type_id
     *
     * @return the value of news_type.type_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_type.type_id
     *
     * @param typeId the value for news_type.type_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}