package cn.hshb.web.biz.mybatis.model;

public class PageAccessQuantityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_access_quantity.page_information_id
     *
     * @mbggenerated Thu Aug 06 09:38:41 CST 2015
     */
    private String pageInformationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_access_quantity.page_information_id
     *
     * @return the value of page_access_quantity.page_information_id
     *
     * @mbggenerated Thu Aug 06 09:38:41 CST 2015
     */
    public String getPageInformationId() {
        return pageInformationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_access_quantity.page_information_id
     *
     * @param pageInformationId the value for page_access_quantity.page_information_id
     *
     * @mbggenerated Thu Aug 06 09:38:41 CST 2015
     */
    public void setPageInformationId(String pageInformationId) {
        this.pageInformationId = pageInformationId == null ? null : pageInformationId.trim();
    }
}