package cn.hshb.web.biz.mybatis.model;

import java.util.Date;

public class PlatImage extends PlatImageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_image.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_image.module_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String moduleFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_image.pic_path
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_image.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_image.is_public
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer isPublic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_image.member_id
     *
     * @return the value of plat_image.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_image.member_id
     *
     * @param memberId the value for plat_image.member_id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_image.module_flag
     *
     * @return the value of plat_image.module_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getModuleFlag() {
        return moduleFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_image.module_flag
     *
     * @param moduleFlag the value for plat_image.module_flag
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setModuleFlag(String moduleFlag) {
        this.moduleFlag = moduleFlag == null ? null : moduleFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_image.pic_path
     *
     * @return the value of plat_image.pic_path
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_image.pic_path
     *
     * @param picPath the value for plat_image.pic_path
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_image.created_time
     *
     * @return the value of plat_image.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_image.created_time
     *
     * @param createdTime the value for plat_image.created_time
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_image.is_public
     *
     * @return the value of plat_image.is_public
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_image.is_public
     *
     * @param isPublic the value for plat_image.is_public
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }
}