package cn.hshb.web.biz.mybatis.model;

public class RecruitPositionTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_position_type.id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_position_type.id
     *
     * @return the value of recruit_position_type.id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_position_type.id
     *
     * @param id the value for recruit_position_type.id
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }
}