package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.BaseRegion;
import cn.hshb.web.biz.mybatis.model.BaseRegionExample;
import cn.hshb.web.biz.mybatis.model.BaseRegionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseRegionMapper extends HshbBaseMapper<BaseRegion> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(BaseRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(BaseRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(BaseRegionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(BaseRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(BaseRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<BaseRegion> selectByExample(BaseRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    BaseRegion selectByPrimaryKey(BaseRegionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") BaseRegion record, @Param("example") BaseRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") BaseRegion record, @Param("example") BaseRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(BaseRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_region
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(BaseRegion record);
}