package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.BusinessRaiders;
import cn.hshb.web.biz.mybatis.model.BusinessRaidersExample;
import cn.hshb.web.biz.mybatis.model.BusinessRaidersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessRaidersMapper extends HshbBaseMapper<BusinessRaiders> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(BusinessRaidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(BusinessRaidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(BusinessRaidersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(BusinessRaiders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(BusinessRaiders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<BusinessRaiders> selectByExample(BusinessRaidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    BusinessRaiders selectByPrimaryKey(BusinessRaidersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") BusinessRaiders record, @Param("example") BusinessRaidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") BusinessRaiders record, @Param("example") BusinessRaidersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(BusinessRaiders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_raiders
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(BusinessRaiders record);
}