package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CityForNewHouse;
import cn.hshb.web.biz.mybatis.model.CityForNewHouseExample;
import cn.hshb.web.biz.mybatis.model.CityForNewHouseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityForNewHouseMapper extends HshbBaseMapper<CityForNewHouse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CityForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CityForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CityForNewHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CityForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CityForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CityForNewHouse> selectByExample(CityForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CityForNewHouse selectByPrimaryKey(CityForNewHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CityForNewHouse record, @Param("example") CityForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CityForNewHouse record, @Param("example") CityForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CityForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CityForNewHouse record);
}