package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonOrientations;
import cn.hshb.web.biz.mybatis.model.CommonOrientationsExample;
import cn.hshb.web.biz.mybatis.model.CommonOrientationsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonOrientationsMapper extends HshbBaseMapper<CommonOrientations> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonOrientationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonOrientationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonOrientationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonOrientations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonOrientations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonOrientations> selectByExample(CommonOrientationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonOrientations selectByPrimaryKey(CommonOrientationsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonOrientations record, @Param("example") CommonOrientationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonOrientations record, @Param("example") CommonOrientationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonOrientations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_orientations
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonOrientations record);
}