package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonLoanRate;
import cn.hshb.web.biz.mybatis.model.CommonLoanRateExample;
import cn.hshb.web.biz.mybatis.model.CommonLoanRateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonLoanRateMapper extends HshbBaseMapper<CommonLoanRate> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonLoanRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonLoanRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonLoanRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonLoanRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonLoanRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonLoanRate> selectByExample(CommonLoanRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonLoanRate selectByPrimaryKey(CommonLoanRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonLoanRate record, @Param("example") CommonLoanRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonLoanRate record, @Param("example") CommonLoanRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonLoanRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_loan_rate
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonLoanRate record);
}