package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonSubway;
import cn.hshb.web.biz.mybatis.model.CommonSubwayExample;
import cn.hshb.web.biz.mybatis.model.CommonSubwayKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonSubwayMapper extends HshbBaseMapper<CommonSubway> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonSubwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonSubwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonSubwayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonSubway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonSubway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonSubway> selectByExample(CommonSubwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonSubway selectByPrimaryKey(CommonSubwayKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonSubway record, @Param("example") CommonSubwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonSubway record, @Param("example") CommonSubwayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonSubway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_subway
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonSubway record);
    
    /* 自定义 */
    /**
     * 搜索地铁线路
     * @return
     */
    List<CommonSubway> selectBySubway();
}