package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonLiveFacility;
import cn.hshb.web.biz.mybatis.model.CommonLiveFacilityExample;
import cn.hshb.web.biz.mybatis.model.CommonLiveFacilityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonLiveFacilityMapper extends HshbBaseMapper<CommonLiveFacility> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonLiveFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonLiveFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonLiveFacilityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonLiveFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonLiveFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonLiveFacility> selectByExample(CommonLiveFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonLiveFacility selectByPrimaryKey(CommonLiveFacilityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonLiveFacility record, @Param("example") CommonLiveFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonLiveFacility record, @Param("example") CommonLiveFacilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonLiveFacility record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_live_facility
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonLiveFacility record);
}