package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonActivity;
import cn.hshb.web.biz.mybatis.model.CommonActivityExample;
import cn.hshb.web.biz.mybatis.model.CommonActivityKey;
import cn.hshb.web.biz.mybatis.model.CommonActivityWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonActivityMapper extends HshbBaseMapper<CommonActivity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonActivityWithBLOBs> selectByExampleWithBLOBs(CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonActivity> selectByExample(CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonActivityWithBLOBs selectByPrimaryKey(CommonActivityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonActivityWithBLOBs record, @Param("example") CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleWithBLOBs(@Param("record") CommonActivityWithBLOBs record, @Param("example") CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonActivity record, @Param("example") CommonActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(CommonActivityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_activity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonActivity record);
}