package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonAdandactivitybar;
import cn.hshb.web.biz.mybatis.model.CommonAdandactivitybarExample;
import cn.hshb.web.biz.mybatis.model.CommonAdandactivitybarKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonAdandactivitybarMapper extends HshbBaseMapper<CommonAdandactivitybar> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonAdandactivitybarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonAdandactivitybarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonAdandactivitybarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonAdandactivitybar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonAdandactivitybar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonAdandactivitybar> selectByExample(CommonAdandactivitybarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonAdandactivitybar selectByPrimaryKey(CommonAdandactivitybarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonAdandactivitybar record, @Param("example") CommonAdandactivitybarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonAdandactivitybar record, @Param("example") CommonAdandactivitybarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonAdandactivitybar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_adandactivitybar
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonAdandactivitybar record);
}