package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonCbdRelation;
import cn.hshb.web.biz.mybatis.model.CommonCbdRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonCbdRelationMapper extends HshbBaseMapper<CommonCbdRelation> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonCbdRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonCbdRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonCbdRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonCbdRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonCbdRelation> selectByExample(CommonCbdRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonCbdRelation record, @Param("example") CommonCbdRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_relation
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonCbdRelation record, @Param("example") CommonCbdRelationExample example);
}