package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonHousetype;
import cn.hshb.web.biz.mybatis.model.CommonHousetypeExample;
import cn.hshb.web.biz.mybatis.model.CommonHousetypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonHousetypeMapper extends HshbBaseMapper<CommonHousetype> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonHousetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonHousetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonHousetypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonHousetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonHousetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonHousetype> selectByExample(CommonHousetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonHousetype selectByPrimaryKey(CommonHousetypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonHousetype record, @Param("example") CommonHousetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonHousetype record, @Param("example") CommonHousetypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonHousetype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_housetype
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonHousetype record);
}