package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonCbdWebsite;
import cn.hshb.web.biz.mybatis.model.CommonCbdWebsiteExample;
import cn.hshb.web.biz.mybatis.model.CommonCbdWebsiteKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonCbdWebsiteMapper extends HshbBaseMapper<CommonCbdWebsite> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonCbdWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonCbdWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonCbdWebsiteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonCbdWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonCbdWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonCbdWebsite> selectByExample(CommonCbdWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonCbdWebsite selectByPrimaryKey(CommonCbdWebsiteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonCbdWebsite record, @Param("example") CommonCbdWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonCbdWebsite record, @Param("example") CommonCbdWebsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonCbdWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_cbd_website
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonCbdWebsite record);
    
    /** 自定义 **/
    /**
     * 根据城区Id,返回网站商圈
     * @param countyId
     * @return
     */
    List<CommonCbdWebsite> selectByWebsiteCBD(String countyId); 
    
    /**
     * 根据ERP商圈，返回网站商圈
     * @param cbdErpId
     * @return
     */
    CommonCbdWebsite selectCbdIdByWebsiteCbd(int cbdErpId);
    
    /**
     * 返回所有网站商圈
     * @return
     */
    List<CommonCbdWebsite> selectAllCbdWebsite();
}