package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CommonQuestionStrategyType;
import cn.hshb.web.biz.mybatis.model.CommonQuestionStrategyTypeExample;
import cn.hshb.web.biz.mybatis.model.CommonQuestionStrategyTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonQuestionStrategyTypeMapper extends HshbBaseMapper<CommonQuestionStrategyType> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CommonQuestionStrategyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CommonQuestionStrategyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CommonQuestionStrategyTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CommonQuestionStrategyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CommonQuestionStrategyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CommonQuestionStrategyType> selectByExample(CommonQuestionStrategyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CommonQuestionStrategyType selectByPrimaryKey(CommonQuestionStrategyTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CommonQuestionStrategyType record, @Param("example") CommonQuestionStrategyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CommonQuestionStrategyType record, @Param("example") CommonQuestionStrategyTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CommonQuestionStrategyType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_question_strategy_type
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CommonQuestionStrategyType record);
}