package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CompanyIntroduce;
import cn.hshb.web.biz.mybatis.model.CompanyIntroduceExample;
import cn.hshb.web.biz.mybatis.model.CompanyIntroduceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyIntroduceMapper extends HshbBaseMapper<CompanyIntroduce> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CompanyIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CompanyIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CompanyIntroduceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CompanyIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CompanyIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CompanyIntroduce> selectByExample(CompanyIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CompanyIntroduce selectByPrimaryKey(CompanyIntroduceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CompanyIntroduce record, @Param("example") CompanyIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CompanyIntroduce record, @Param("example") CompanyIntroduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CompanyIntroduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_introduce
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CompanyIntroduce record);
}