package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CompanyContactus;
import cn.hshb.web.biz.mybatis.model.CompanyContactusExample;
import cn.hshb.web.biz.mybatis.model.CompanyContactusKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyContactusMapper extends HshbBaseMapper<CompanyContactus> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CompanyContactusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CompanyContactusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CompanyContactusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CompanyContactus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CompanyContactus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CompanyContactus> selectByExample(CompanyContactusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CompanyContactus selectByPrimaryKey(CompanyContactusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CompanyContactus record, @Param("example") CompanyContactusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CompanyContactus record, @Param("example") CompanyContactusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CompanyContactus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_contactus
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CompanyContactus record);
}