package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.CountyForNewHouse;
import cn.hshb.web.biz.mybatis.model.CountyForNewHouseExample;
import cn.hshb.web.biz.mybatis.model.CountyForNewHouseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountyForNewHouseMapper extends HshbBaseMapper<CountyForNewHouse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(CountyForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(CountyForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(CountyForNewHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(CountyForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(CountyForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<CountyForNewHouse> selectByExample(CountyForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    CountyForNewHouse selectByPrimaryKey(CountyForNewHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") CountyForNewHouse record, @Param("example") CountyForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") CountyForNewHouse record, @Param("example") CountyForNewHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(CountyForNewHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county_for_new_house
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(CountyForNewHouse record);
}