package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EfwBusinessModule;
import cn.hshb.web.biz.mybatis.model.EfwBusinessModuleExample;
import cn.hshb.web.biz.mybatis.model.EfwBusinessModuleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EfwBusinessModuleMapper extends HshbBaseMapper<EfwBusinessModule> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EfwBusinessModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EfwBusinessModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EfwBusinessModuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EfwBusinessModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EfwBusinessModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EfwBusinessModule> selectByExample(EfwBusinessModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EfwBusinessModule selectByPrimaryKey(EfwBusinessModuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EfwBusinessModule record, @Param("example") EfwBusinessModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EfwBusinessModule record, @Param("example") EfwBusinessModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EfwBusinessModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EfwBusinessModule record);
}