package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EfwBusinessModuleMap;
import cn.hshb.web.biz.mybatis.model.EfwBusinessModuleMapExample;
import cn.hshb.web.biz.mybatis.model.EfwBusinessModuleMapKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EfwBusinessModuleMapMapper extends HshbBaseMapper<EfwBusinessModuleMap> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EfwBusinessModuleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EfwBusinessModuleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EfwBusinessModuleMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EfwBusinessModuleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EfwBusinessModuleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EfwBusinessModuleMap> selectByExample(EfwBusinessModuleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EfwBusinessModuleMap selectByPrimaryKey(EfwBusinessModuleMapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EfwBusinessModuleMap record, @Param("example") EfwBusinessModuleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EfwBusinessModuleMap record, @Param("example") EfwBusinessModuleMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EfwBusinessModuleMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_business_module_map
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EfwBusinessModuleMap record);
}