package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EfwDataRoleAuthority;
import cn.hshb.web.biz.mybatis.model.EfwDataRoleAuthorityExample;
import cn.hshb.web.biz.mybatis.model.EfwDataRoleAuthorityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EfwDataRoleAuthorityMapper extends HshbBaseMapper<EfwDataRoleAuthority> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EfwDataRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EfwDataRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EfwDataRoleAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EfwDataRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EfwDataRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EfwDataRoleAuthority> selectByExample(EfwDataRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EfwDataRoleAuthority selectByPrimaryKey(EfwDataRoleAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EfwDataRoleAuthority record, @Param("example") EfwDataRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EfwDataRoleAuthority record, @Param("example") EfwDataRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EfwDataRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_data_role_authority
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EfwDataRoleAuthority record);
}