package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EfwSourseEntity;
import cn.hshb.web.biz.mybatis.model.EfwSourseEntityExample;
import cn.hshb.web.biz.mybatis.model.EfwSourseEntityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EfwSourseEntityMapper extends HshbBaseMapper<EfwSourseEntity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EfwSourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EfwSourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EfwSourseEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EfwSourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EfwSourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EfwSourseEntity> selectByExample(EfwSourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EfwSourseEntity selectByPrimaryKey(EfwSourseEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EfwSourseEntity record, @Param("example") EfwSourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EfwSourseEntity record, @Param("example") EfwSourseEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EfwSourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_sourse_entity
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EfwSourseEntity record);
}