package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EfwUserDataRole;
import cn.hshb.web.biz.mybatis.model.EfwUserDataRoleExample;
import cn.hshb.web.biz.mybatis.model.EfwUserDataRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EfwUserDataRoleMapper extends HshbBaseMapper<EfwUserDataRole> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EfwUserDataRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EfwUserDataRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EfwUserDataRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EfwUserDataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EfwUserDataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EfwUserDataRole> selectByExample(EfwUserDataRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EfwUserDataRole selectByPrimaryKey(EfwUserDataRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EfwUserDataRole record, @Param("example") EfwUserDataRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EfwUserDataRole record, @Param("example") EfwUserDataRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EfwUserDataRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table efw_user_data_role
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EfwUserDataRole record);
}