package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.EntrustRenthouse;
import cn.hshb.web.biz.mybatis.model.EntrustRenthouseExample;
import cn.hshb.web.biz.mybatis.model.EntrustRenthouseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntrustRenthouseMapper extends HshbBaseMapper<EntrustRenthouse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int countByExample(EntrustRenthouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByExample(EntrustRenthouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int deleteByPrimaryKey(EntrustRenthouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insert(EntrustRenthouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int insertSelective(EntrustRenthouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    List<EntrustRenthouse> selectByExample(EntrustRenthouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    EntrustRenthouse selectByPrimaryKey(EntrustRenthouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EntrustRenthouse record, @Param("example") EntrustRenthouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EntrustRenthouse record, @Param("example") EntrustRenthouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EntrustRenthouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entrust_renthouse
     *
     * @mbggenerated Wed Jul 08 19:17:39 GMT+08:00 2015
     */
    int updateByPrimaryKey(EntrustRenthouse record);
}