package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwActionLog;
import cn.hshb.web.biz.mybatis.model.FwActionLogExample;
import cn.hshb.web.biz.mybatis.model.FwActionLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwActionLogMapper extends HshbBaseMapper<FwActionLog> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwActionLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwActionLog> selectByExample(FwActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwActionLog selectByPrimaryKey(FwActionLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwActionLog record, @Param("example") FwActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwActionLog record, @Param("example") FwActionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_action_log
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwActionLog record);
}