package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwCategory;
import cn.hshb.web.biz.mybatis.model.FwCategoryExample;
import cn.hshb.web.biz.mybatis.model.FwCategoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwCategoryMapper extends HshbBaseMapper<FwCategory> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwCategory> selectByExample(FwCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwCategory selectByPrimaryKey(FwCategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwCategory record, @Param("example") FwCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwCategory record, @Param("example") FwCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_category
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwCategory record);
}