package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwErrors;
import cn.hshb.web.biz.mybatis.model.FwErrorsExample;
import cn.hshb.web.biz.mybatis.model.FwErrorsKey;
import cn.hshb.web.biz.mybatis.model.FwErrorsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwErrorsMapper extends HshbBaseMapper<FwErrors> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwErrorsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwErrorsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwErrorsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwErrorsWithBLOBs> selectByExampleWithBLOBs(FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwErrors> selectByExample(FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwErrorsWithBLOBs selectByPrimaryKey(FwErrorsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwErrorsWithBLOBs record, @Param("example") FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleWithBLOBs(@Param("record") FwErrorsWithBLOBs record, @Param("example") FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwErrors record, @Param("example") FwErrorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwErrorsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(FwErrorsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_errors
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwErrors record);
}