package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwLogin;
import cn.hshb.web.biz.mybatis.model.FwLoginExample;
import cn.hshb.web.biz.mybatis.model.FwLoginKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwLoginMapper extends HshbBaseMapper<FwLogin> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwLogin> selectByExample(FwLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwLogin selectByPrimaryKey(FwLoginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwLogin record, @Param("example") FwLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwLogin record, @Param("example") FwLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_login
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwLogin record);
}