package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwSchedule;
import cn.hshb.web.biz.mybatis.model.FwScheduleExample;
import cn.hshb.web.biz.mybatis.model.FwScheduleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwScheduleMapper extends HshbBaseMapper<FwSchedule> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwSchedule> selectByExample(FwScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwSchedule selectByPrimaryKey(FwScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwSchedule record, @Param("example") FwScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwSchedule record, @Param("example") FwScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_schedule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwSchedule record);
}