package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwSource;
import cn.hshb.web.biz.mybatis.model.FwSourceExample;
import cn.hshb.web.biz.mybatis.model.FwSourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwSourceMapper extends HshbBaseMapper<FwSource> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwSourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwSource> selectByExample(FwSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwSource selectByPrimaryKey(FwSourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwSource record, @Param("example") FwSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwSource record, @Param("example") FwSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_source
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwSource record);
}