package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwSrcAction;
import cn.hshb.web.biz.mybatis.model.FwSrcActionExample;
import cn.hshb.web.biz.mybatis.model.FwSrcActionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwSrcActionMapper extends HshbBaseMapper<FwSrcAction> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwSrcActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwSrcActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwSrcActionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwSrcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwSrcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwSrcAction> selectByExample(FwSrcActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwSrcAction selectByPrimaryKey(FwSrcActionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwSrcAction record, @Param("example") FwSrcActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwSrcAction record, @Param("example") FwSrcActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwSrcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_src_action
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwSrcAction record);
}