package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.FwSystemIp;
import cn.hshb.web.biz.mybatis.model.FwSystemIpExample;
import cn.hshb.web.biz.mybatis.model.FwSystemIpKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FwSystemIpMapper extends HshbBaseMapper<FwSystemIp> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(FwSystemIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(FwSystemIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(FwSystemIpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(FwSystemIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(FwSystemIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<FwSystemIp> selectByExample(FwSystemIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    FwSystemIp selectByPrimaryKey(FwSystemIpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") FwSystemIp record, @Param("example") FwSystemIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") FwSystemIp record, @Param("example") FwSystemIpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(FwSystemIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fw_system_ip
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(FwSystemIp record);
}