package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseRentBrowseAnalyse;
import cn.hshb.web.biz.mybatis.model.HouseRentBrowseAnalyseExample;
import cn.hshb.web.biz.mybatis.model.HouseRentBrowseAnalyseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseRentBrowseAnalyseMapper extends HshbBaseMapper<HouseRentBrowseAnalyse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseRentBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseRentBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseRentBrowseAnalyseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseRentBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseRentBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseRentBrowseAnalyse> selectByExample(HouseRentBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseRentBrowseAnalyse selectByPrimaryKey(HouseRentBrowseAnalyseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseRentBrowseAnalyse record, @Param("example") HouseRentBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseRentBrowseAnalyse record, @Param("example") HouseRentBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseRentBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_rent_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseRentBrowseAnalyse record);
}