package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseAppraise;
import cn.hshb.web.biz.mybatis.model.HouseAppraiseExample;
import cn.hshb.web.biz.mybatis.model.HouseAppraiseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseAppraiseMapper extends HshbBaseMapper<HouseAppraise> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseAppraiseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseAppraise> selectByExample(HouseAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseAppraise selectByPrimaryKey(HouseAppraiseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseAppraise record, @Param("example") HouseAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseAppraise record, @Param("example") HouseAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_appraise
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseAppraise record);
    
    /* 自定义 */
    /**
     * 根据房源id获取房源评价及经纪人Id
     * @param houseId
     * @return
     */
    List<HouseAppraise> selectHouseAppraiseByHouseId(String houseId);
    
    /**
     * 根据房源上架id获取房源评价及经纪人Id
     * @param houseId
     * @return
     */
    List<HouseAppraise> selectHouseAppraiseByShelvingId(String shelvingId);
}