package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseSecondBrowseAnalyse;
import cn.hshb.web.biz.mybatis.model.HouseSecondBrowseAnalyseExample;
import cn.hshb.web.biz.mybatis.model.HouseSecondBrowseAnalyseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseSecondBrowseAnalyseMapper extends HshbBaseMapper<HouseSecondBrowseAnalyse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseSecondBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseSecondBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseSecondBrowseAnalyseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseSecondBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseSecondBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseSecondBrowseAnalyse> selectByExample(HouseSecondBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseSecondBrowseAnalyse selectByPrimaryKey(HouseSecondBrowseAnalyseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseSecondBrowseAnalyse record, @Param("example") HouseSecondBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseSecondBrowseAnalyse record, @Param("example") HouseSecondBrowseAnalyseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseSecondBrowseAnalyse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_browse_analyse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseSecondBrowseAnalyse record);
}