package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseCommunityAveragePrice;
import cn.hshb.web.biz.mybatis.model.HouseCommunityAveragePriceExample;
import cn.hshb.web.biz.mybatis.model.HouseCommunityAveragePriceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseCommunityAveragePriceMapper extends HshbBaseMapper<HouseCommunityAveragePrice> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseCommunityAveragePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseCommunityAveragePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseCommunityAveragePriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseCommunityAveragePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseCommunityAveragePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseCommunityAveragePrice> selectByExample(HouseCommunityAveragePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseCommunityAveragePrice selectByPrimaryKey(HouseCommunityAveragePriceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseCommunityAveragePrice record, @Param("example") HouseCommunityAveragePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseCommunityAveragePrice record, @Param("example") HouseCommunityAveragePriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseCommunityAveragePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_average_price
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseCommunityAveragePrice record);
    
    /* 自定义 */
    /**
     * 根据小区Id,查找近4个月的平均价格
     * @param comunityId
     * @return
     */
    List<HouseCommunityAveragePrice> selectPriceTrendSixMonth(String comunityId);
}