package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseCommunitySubwayStationMapping;
import cn.hshb.web.biz.mybatis.model.HouseCommunitySubwayStationMappingExample;
import cn.hshb.web.biz.mybatis.model.HouseCommunitySubwayStationMappingKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HouseCommunitySubwayStationMappingMapper extends HshbBaseMapper<HouseCommunitySubwayStationMapping> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseCommunitySubwayStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseCommunitySubwayStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseCommunitySubwayStationMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseCommunitySubwayStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseCommunitySubwayStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseCommunitySubwayStationMapping> selectByExample(HouseCommunitySubwayStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseCommunitySubwayStationMapping selectByPrimaryKey(HouseCommunitySubwayStationMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseCommunitySubwayStationMapping record, @Param("example") HouseCommunitySubwayStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseCommunitySubwayStationMapping record, @Param("example") HouseCommunitySubwayStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseCommunitySubwayStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_subway_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseCommunitySubwayStationMapping record);
    
    /* 自定义 */
    /**
     * 地铁 关联
     * @param map
     * @return
     */
    List<HouseCommunitySubwayStationMapping> selectAssociateByMap(Map<String, String> map);
}