package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseCommunityHospitalMapping;
import cn.hshb.web.biz.mybatis.model.HouseCommunityHospitalMappingExample;
import cn.hshb.web.biz.mybatis.model.HouseCommunityHospitalMappingKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HouseCommunityHospitalMappingMapper extends HshbBaseMapper<HouseCommunityHospitalMapping> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseCommunityHospitalMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseCommunityHospitalMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseCommunityHospitalMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseCommunityHospitalMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseCommunityHospitalMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseCommunityHospitalMapping> selectByExample(HouseCommunityHospitalMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseCommunityHospitalMapping selectByPrimaryKey(HouseCommunityHospitalMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseCommunityHospitalMapping record, @Param("example") HouseCommunityHospitalMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseCommunityHospitalMapping record, @Param("example") HouseCommunityHospitalMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseCommunityHospitalMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_hospital_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseCommunityHospitalMapping record);
    
    /* 自定义 */
    /**
     * 医院关联
     * @param map
     * @return
     */
    List<HouseCommunityHospitalMapping> selectAssociateByMap(Map<String, String> map);
}