package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseNewhouse;
import cn.hshb.web.biz.mybatis.model.HouseNewhouseExample;
import cn.hshb.web.biz.mybatis.model.HouseNewhouseKey;
import cn.hshb.web.biz.mybatis.model.HouseNewhouseWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HouseNewhouseMapper extends HshbBaseMapper<HouseNewhouse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseNewhouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseNewhouseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseNewhouseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseNewhouseWithBLOBs> selectByExampleWithBLOBs(HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseNewhouse> selectByExample(HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseNewhouseWithBLOBs selectByPrimaryKey(HouseNewhouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseNewhouseWithBLOBs record, @Param("example") HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleWithBLOBs(@Param("record") HouseNewhouseWithBLOBs record, @Param("example") HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseNewhouse record, @Param("example") HouseNewhouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseNewhouseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(HouseNewhouseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_newhouse
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseNewhouse record);
}