package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.HouseCommunityStationMapping;
import cn.hshb.web.biz.mybatis.model.HouseCommunityStationMappingExample;
import cn.hshb.web.biz.mybatis.model.HouseCommunityStationMappingKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HouseCommunityStationMappingMapper extends HshbBaseMapper<HouseCommunityStationMapping> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseCommunityStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseCommunityStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseCommunityStationMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseCommunityStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseCommunityStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseCommunityStationMapping> selectByExample(HouseCommunityStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseCommunityStationMapping selectByPrimaryKey(HouseCommunityStationMappingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseCommunityStationMapping record, @Param("example") HouseCommunityStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseCommunityStationMapping record, @Param("example") HouseCommunityStationMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseCommunityStationMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_community_station_mapping
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseCommunityStationMapping record);
    
    /**
     * 关联查询,车站信息
     * @param map
     * @return
     */
    List<HouseCommunityStationMapping> selectAssociateByMap(Map<String, String> map);
}