package cn.hshb.web.biz.mybatis.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cn.hshb.web.biz.mybatis.model.HouseSecondHandHouse;
import cn.hshb.web.biz.mybatis.model.HouseSecondHandHouseExample;
import cn.hshb.web.biz.mybatis.model.HouseSecondHandHouseKey;

public interface HouseSecondHandHouseMapper extends HshbBaseMapper<HouseSecondHandHouse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(HouseSecondHandHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(HouseSecondHandHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(HouseSecondHandHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(HouseSecondHandHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(HouseSecondHandHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<HouseSecondHandHouse> selectByExample(HouseSecondHandHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    HouseSecondHandHouse selectByPrimaryKey(HouseSecondHandHouseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") HouseSecondHandHouse record, @Param("example") HouseSecondHandHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") HouseSecondHandHouse record, @Param("example") HouseSecondHandHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(HouseSecondHandHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_second_hand_house
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(HouseSecondHandHouse record);

    
    /*****************以下自定义方法********************/
    /**
     * 查询带关联数据的房源信息
     * @param condition
     * @return
     */
    List<HouseSecondHandHouse> selectAssociateByExample(HouseSecondHandHouseExample condition);
    
    /**
     * 为二手房列表查询房源数据
     * @param condition	查询条件
     * @return
     */
    List<HouseSecondHandHouse> selectHouseForDetailByMap(Map<String, Object> condition);
    
    /**
     * 为二手房详情查询数据
     * @param condition	查询条件
     * @return
     */
    List<HouseSecondHandHouse> selectHouseForListByMap(Map<String, Object> condition);
}