package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.MemberIntegralTable;
import cn.hshb.web.biz.mybatis.model.MemberIntegralTableExample;
import cn.hshb.web.biz.mybatis.model.MemberIntegralTableKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberIntegralTableMapper extends HshbBaseMapper<MemberIntegralTable> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(MemberIntegralTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(MemberIntegralTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(MemberIntegralTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(MemberIntegralTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(MemberIntegralTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<MemberIntegralTable> selectByExample(MemberIntegralTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    MemberIntegralTable selectByPrimaryKey(MemberIntegralTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") MemberIntegralTable record, @Param("example") MemberIntegralTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") MemberIntegralTable record, @Param("example") MemberIntegralTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(MemberIntegralTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integral_table
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(MemberIntegralTable record);
}