package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.MemberIntegrateRule;
import cn.hshb.web.biz.mybatis.model.MemberIntegrateRuleExample;
import cn.hshb.web.biz.mybatis.model.MemberIntegrateRuleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberIntegrateRuleMapper extends HshbBaseMapper<MemberIntegrateRule> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(MemberIntegrateRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(MemberIntegrateRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(MemberIntegrateRuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(MemberIntegrateRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(MemberIntegrateRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<MemberIntegrateRule> selectByExample(MemberIntegrateRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    MemberIntegrateRule selectByPrimaryKey(MemberIntegrateRuleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") MemberIntegrateRule record, @Param("example") MemberIntegrateRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") MemberIntegrateRule record, @Param("example") MemberIntegrateRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(MemberIntegrateRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_integrate_rule
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(MemberIntegrateRule record);
}