package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.MemberBrowsedRhHistoryBeforeBespeak;
import cn.hshb.web.biz.mybatis.model.MemberBrowsedRhHistoryBeforeBespeakExample;
import cn.hshb.web.biz.mybatis.model.MemberBrowsedRhHistoryBeforeBespeakKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberBrowsedRhHistoryBeforeBespeakMapper extends HshbBaseMapper<MemberBrowsedRhHistoryBeforeBespeak> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(MemberBrowsedRhHistoryBeforeBespeakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(MemberBrowsedRhHistoryBeforeBespeakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(MemberBrowsedRhHistoryBeforeBespeakKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(MemberBrowsedRhHistoryBeforeBespeak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(MemberBrowsedRhHistoryBeforeBespeak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<MemberBrowsedRhHistoryBeforeBespeak> selectByExample(MemberBrowsedRhHistoryBeforeBespeakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    MemberBrowsedRhHistoryBeforeBespeak selectByPrimaryKey(MemberBrowsedRhHistoryBeforeBespeakKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") MemberBrowsedRhHistoryBeforeBespeak record, @Param("example") MemberBrowsedRhHistoryBeforeBespeakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") MemberBrowsedRhHistoryBeforeBespeak record, @Param("example") MemberBrowsedRhHistoryBeforeBespeakExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(MemberBrowsedRhHistoryBeforeBespeak record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_browsed_rh_history_before_bespeak
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(MemberBrowsedRhHistoryBeforeBespeak record);
}