package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.MemberCollection;
import cn.hshb.web.biz.mybatis.model.MemberCollectionExample;
import cn.hshb.web.biz.mybatis.model.MemberCollectionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberCollectionMapper extends HshbBaseMapper<MemberCollection> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(MemberCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(MemberCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(MemberCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(MemberCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(MemberCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<MemberCollection> selectByExample(MemberCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    MemberCollection selectByPrimaryKey(MemberCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") MemberCollection record, @Param("example") MemberCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") MemberCollection record, @Param("example") MemberCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(MemberCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_collection
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(MemberCollection record);
}