package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseRent;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseRentExample;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseRentKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface PartnerBaiduHouseRentMapper extends HshbBaseMapper<PartnerBaiduHouseRent> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(PartnerBaiduHouseRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(PartnerBaiduHouseRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(PartnerBaiduHouseRentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(PartnerBaiduHouseRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(PartnerBaiduHouseRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<PartnerBaiduHouseRent> selectByExample(PartnerBaiduHouseRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    PartnerBaiduHouseRent selectByPrimaryKey(PartnerBaiduHouseRentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") PartnerBaiduHouseRent record, @Param("example") PartnerBaiduHouseRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") PartnerBaiduHouseRent record, @Param("example") PartnerBaiduHouseRentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PartnerBaiduHouseRent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_rent
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(PartnerBaiduHouseRent record);
    
    /* 自定义 */
    /**
     * 返回数据
     * @param maxNumber 返回数据上限
     * @return
     */
    List<PartnerBaiduHouseRent> selectAllData(int maxNumber);
    
    /**
     * 返回需要删除数据
     * @return	
     */
    List<PartnerBaiduHouseRent> selectAllDeleteData();
}