package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.PartnerBaiduCommunity;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduCommunityExample;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduCommunityKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerBaiduCommunityMapper extends HshbBaseMapper<PartnerBaiduCommunity> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(PartnerBaiduCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(PartnerBaiduCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(PartnerBaiduCommunityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(PartnerBaiduCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(PartnerBaiduCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<PartnerBaiduCommunity> selectByExample(PartnerBaiduCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    PartnerBaiduCommunity selectByPrimaryKey(PartnerBaiduCommunityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") PartnerBaiduCommunity record, @Param("example") PartnerBaiduCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") PartnerBaiduCommunity record, @Param("example") PartnerBaiduCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PartnerBaiduCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_community
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(PartnerBaiduCommunity record);
    
    /* 自定义 */
    /**
     * 返回数据
     * @param maxNumber 数据上限
     * @return
     */
    List<PartnerBaiduCommunity> selectBaiduCommunityData(int maxNumber);
}