package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseSecond;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseSecondExample;
import cn.hshb.web.biz.mybatis.model.PartnerBaiduHouseSecondKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartnerBaiduHouseSecondMapper extends HshbBaseMapper<PartnerBaiduHouseSecond> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(PartnerBaiduHouseSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(PartnerBaiduHouseSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(PartnerBaiduHouseSecondKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(PartnerBaiduHouseSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(PartnerBaiduHouseSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<PartnerBaiduHouseSecond> selectByExample(PartnerBaiduHouseSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    PartnerBaiduHouseSecond selectByPrimaryKey(PartnerBaiduHouseSecondKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") PartnerBaiduHouseSecond record, @Param("example") PartnerBaiduHouseSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") PartnerBaiduHouseSecond record, @Param("example") PartnerBaiduHouseSecondExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PartnerBaiduHouseSecond record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_baidu_house_second
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(PartnerBaiduHouseSecond record);
    
    /* 自定义 */
    /**
     * 返回数据
     * @param maxNumber 返回数据上限
     * @return
     */
    List<PartnerBaiduHouseSecond> selectAllData(int maxNumber);
    
    /**
     * 返回需要提交删除的数据
     * @return
     */
    List<PartnerBaiduHouseSecond> selectAllDeleteData();
}