package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.RecruitCandidate;
import cn.hshb.web.biz.mybatis.model.RecruitCandidateExample;
import cn.hshb.web.biz.mybatis.model.RecruitCandidateKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitCandidateMapper extends HshbBaseMapper<RecruitCandidate> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(RecruitCandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(RecruitCandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(RecruitCandidateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(RecruitCandidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(RecruitCandidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<RecruitCandidate> selectByExample(RecruitCandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    RecruitCandidate selectByPrimaryKey(RecruitCandidateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") RecruitCandidate record, @Param("example") RecruitCandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") RecruitCandidate record, @Param("example") RecruitCandidateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RecruitCandidate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_candidate
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(RecruitCandidate record);
}