package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.RecruitPosition;
import cn.hshb.web.biz.mybatis.model.RecruitPositionExample;
import cn.hshb.web.biz.mybatis.model.RecruitPositionKey;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface RecruitPositionMapper extends HshbBaseMapper<RecruitPosition> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(RecruitPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(RecruitPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(RecruitPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(RecruitPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(RecruitPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<RecruitPosition> selectByExample(RecruitPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    RecruitPosition selectByPrimaryKey(RecruitPositionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") RecruitPosition record, @Param("example") RecruitPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") RecruitPosition record, @Param("example") RecruitPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RecruitPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_position
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(RecruitPosition record);
    
    /* 自定义 */
    /**
     *  根据类型返回不同招聘数据,已更新时间进行倒序 
     * @param map 根据map中的值进行查询,现有条件:typeId(招聘信息类型 )
     * @return
     */
    List<RecruitPosition> selectRecruitPositionMapperByTypeId(Map<String, Object> map);
    
    /**
     * 根据数据Id查询<返回时带有职位名称
     * @param positionId
     * @return
     */
    RecruitPosition selectRecruitPositionMapperById(int positionId);
}