package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.SearchElevator;
import cn.hshb.web.biz.mybatis.model.SearchElevatorExample;
import cn.hshb.web.biz.mybatis.model.SearchElevatorKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchElevatorMapper extends HshbBaseMapper<SearchElevator> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(SearchElevatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(SearchElevatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(SearchElevatorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(SearchElevator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(SearchElevator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<SearchElevator> selectByExample(SearchElevatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    SearchElevator selectByPrimaryKey(SearchElevatorKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") SearchElevator record, @Param("example") SearchElevatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") SearchElevator record, @Param("example") SearchElevatorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(SearchElevator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_elevator
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(SearchElevator record);
}