package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.SearchField;
import cn.hshb.web.biz.mybatis.model.SearchFieldExample;
import cn.hshb.web.biz.mybatis.model.SearchFieldKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchFieldMapper extends HshbBaseMapper<SearchField> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(SearchFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(SearchFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(SearchFieldKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(SearchField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(SearchField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<SearchField> selectByExample(SearchFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    SearchField selectByPrimaryKey(SearchFieldKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") SearchField record, @Param("example") SearchFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") SearchField record, @Param("example") SearchFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(SearchField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_field
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(SearchField record);
}