package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.SearchFiveyear;
import cn.hshb.web.biz.mybatis.model.SearchFiveyearExample;
import cn.hshb.web.biz.mybatis.model.SearchFiveyearKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchFiveyearMapper extends HshbBaseMapper<SearchFiveyear> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(SearchFiveyearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(SearchFiveyearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(SearchFiveyearKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(SearchFiveyear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(SearchFiveyear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<SearchFiveyear> selectByExample(SearchFiveyearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    SearchFiveyear selectByPrimaryKey(SearchFiveyearKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") SearchFiveyear record, @Param("example") SearchFiveyearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") SearchFiveyear record, @Param("example") SearchFiveyearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(SearchFiveyear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_fiveyear
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(SearchFiveyear record);
}