package cn.hshb.web.biz.mybatis.dao;

import cn.hshb.web.biz.mybatis.model.UserCompareHistory;
import cn.hshb.web.biz.mybatis.model.UserCompareHistoryExample;
import cn.hshb.web.biz.mybatis.model.UserCompareHistoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCompareHistoryMapper extends HshbBaseMapper<UserCompareHistory> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int countByExample(UserCompareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByExample(UserCompareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int deleteByPrimaryKey(UserCompareHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insert(UserCompareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int insertSelective(UserCompareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    List<UserCompareHistory> selectByExample(UserCompareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    UserCompareHistory selectByPrimaryKey(UserCompareHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserCompareHistory record, @Param("example") UserCompareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserCompareHistory record, @Param("example") UserCompareHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(UserCompareHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_compare_history
     *
     * @mbggenerated Wed Jul 08 19:17:40 GMT+08:00 2015
     */
    int updateByPrimaryKey(UserCompareHistory record);
}